USE PLACEHOLDER_DB_NAME;
SELECT review_id, cla_episode_id, rev_due_date, rev_date, rev_cyp_involved_care_plan, rev_sw_met_child_views, rev_participation, rev_care_plan_meet_needs, rev_perm_plan, rev_last_iro_contact, prev_permanence, prev_perm_order_date, prev_perm_option, prev_perm_la, convicted_in_year, health_check, health_asmt_date, dental_check_date, immunisations, substance_misuse, intervention_received FROM cla_reviews;
SELECT review_id, permanence_plan FROM care_plan;
SELECT cp_plans_referral_period, legal_gateway_outcome, prev_pre_proc_child, prev_care_proc_child, pre_pro_letter_date, care_pro_letter_date, pre_pro_meetings_num, pre_pro_parents_legal_rep, parents_legal_rep_point_of_issue, court_reference, care_proc_court_hearings, care_proc_short_notice, care_proc_short_notice_reason, la_inital__plan_approved, la_initial_care_plan, la_final_plan_approved, la_final_care_plan FROM plo_silver;
SELECT named_plan_id, ehcp_asmt_id, named_plan_start_date, named_plan_cease_date, named_plan_cease_reason FROM ehcp_named_plan;
SELECT la_person_id, immigration_status, immigration_status_start, immigration_status_end FROM immigration_status;
SELECT asmt_id, asmt_factors FROM assessment_factors;
SELECT cin_referral_id, la_person_id, cin_ref_date, cin_ref_source, cin_ref_outcome, cin_close_reason, cin_close_date, cin_ref_team, cin_ref_worker FROM cin_episodes;
SELECT cp_review_id, cp_review_risks FROM cp_reviews_risks;
SELECT active_ehcp_id, ehcp_request_id, active_ehcp_last_review FROM ehcp_active_plans;
SELECT cp_plan_id, la_person_id, cpp_start_date, cpp_end_date, cpp_team, cpp_worker FROM cp_plans;
SELECT cp_plan_id, cp_visit_id, cp_visit_date, cp_visit_seen, cp_visit_seen_alone, cp_visit_bedroom FROM cp_visits;
SELECT person_child_id, la_person_id, person_child_dob FROM mother;
SELECT send_table_id, send_upn, send_uln, upn_unknown, la_person_id FROM send;
SELECT sw_reg_number, sw_id, sw_epi_start_date, sw_epi_end_date, sw_change_reason, sw_agency, sw_role, sw_caseload, sw_qualification FROM worker;
SELECT cpp_category_id, cp_plan_id, cpp_category, cpp_category_start FROM category_of_abuse;
SELECT cla_visit_id, cla_episode_id, cla_visit_date, cla_visit_seen, cla_visit_seen_alone FROM cla_visits;
SELECT s47_enquiry_id, la_person_id, strat_initiating_s47_date, s47_start_date, s47_completed_date, s47outcome, icpc_date, icpc_outcome, icpc_team, icpc_worker FROM s47_enquiry_icpc;
SELECT sen_need_table_id, active_ehcp_id, active_ehcp_need, active_ehcp_need_rank FROM sen_need;
SELECT la_person_id, person_sex, person_gender, person_ethnicity, person_dob, person_upn, person_upn_unknown, person_send, person_expected_dob, person_death_date, person_is_mother, person_nationality FROM child, person;
SELECT family_id, la_person_id FROM family;
SELECT ehcp_asmt_id, ehcp_request_id, ehcp_asmt_outcome_date, ehcp_asmt_outcome FROM ehcp_assessment;
SELECT ehcp_request_id, send_table_id, ehcp_req_date, ehcp_req_outcome_date, ehcp_req_outcome FROM ehcp_requests;
SELECT cp_review_id, cp_plan_id, cp_rev_due, cp_rev_date, cp_rev_outcome, cp_rev_quorate, cp_rev_participation, cp_rev_cyp_views_quality, cp_rev_sufficient_prog FROM cp_reviews;
SELECT la_person_id, person_disability FROM disability;
SELECT cin_plan_id, la_person_id, cin_plan_Start, cin_plan_end, cin_team, cin_worker FROM cin_plans;
SELECT legal_status_id, la_person_id, legal_status, legal_status_start, legal_status_end FROM legal_status;
SELECT la_person_id, plo_family_id, pre_pro_decision_date, initial_pre_pro_meeting, pre_pro_outcome, date_agree_stepdown_issue, cp_plans_referral_period, legal_gateway_outcome, prev_pre_proc_child, prev_care_proc_child, pre_pro_letter_date, care_pro_letter_date, pre_pro_meetings_num, pre_pro_parents_legal_rep, parents_legal_rep_point_of_issue, court_reference, care_proc_court_hearings, care_proc_short_notice, care_proc_short_notice_reason, la_inital_plan_approved, la_initial_care_plan, la_final_plan_approved, la_final_care_plan FROM pre_proceedings;
SELECT placement_id, cla_episode_id, place_start, place_type, place_urn, place_la, place_provider, place_postcode, place_end, place_change_reason FROM placement;
SELECT contact_id, la_person_id, contact_date, contact_source, contact_outcome FROM contacts;
SELECT eh_episode_id, la_person_id, eh_epi_start_date, eh_epi_end_date, eh_epi_reason, eh_epi_end_reason, eh_epi_org, eh_epi_worker FROM early_help_episodes;
SELECT assessment_id, la_person_id, asmt_start_date, asmt_child_seen, asmt_auth_date, asmt_outcome, asmt_team, asmt_worker FROM assessments;
SELECT missing_episode_id, cla_episode_id, mis_epi_start, mis_epi_type, mis_epi_end, mis_epi_rhi_offered, mis_epi_rhi_accepted FROM missing;
SELECT care_leaver_id, la_person_id, cl_eligibility, cl_in_touch, cl_latest_contact, cl_accommodation, cl_accom_suitable, cl_activity, cl_pathway_plan_rev_date, cl_personal_advisor, cl_team, cl_worker FROM care_leavers;
SELECT permanence_id, la_person_id, adm_decision_date, ffa_cp_decision_date, entered_care_date, placement_order_date, placed_for_adoption_date, matched_date, placed_ffa_cp_date, decision_reversed_date, placed_foster_carer_date, sibling_group, siblings_placed_together, siblings_placed_apart, place_provider_urn, decision_reversed_reason, permanence_order_date, permanence_order_type, guardian_status, guardian_age FROM permanence;
SELECT sdq_id, la_person_id, sdq_completed_date, sdq_reason, sdq_score FROM sdq_scores;
SELECT cin_visit_id, cin_plan_id, cin_visit_date, cin_visit_seen, cin_visit_seen_alone, cin_visit_bedroom FROM cin_visits;
SELECT mosaic_address, la_child_id, mosaic_address_type, mosaic_address_start FROM mosaic_address_tbl;
SELECT cla_episode_id, la_person_id, cla_epi_start, cla_epi_start_reason, cla_epi_ceased, cla_epi_cease_reason, cla_team, cla_worker FROM cla_episodes;
SELECT plo_family_id, pre_pro_decision_date, initial_pre_pro_meeting, pre_pro_outcome, date_agree_stepdown_issue FROM plo_bronze;
