tables:
  - name: Users
    fields:
      - name: id
        type: INTEGER
        cms:
          - liquid_logic
          - mosaic
      - name: name
        type: VARCHAR(100)
        cms:
          - mosaic
  - name: Products
    fields:
      - name: id
        type: INTEGER
        cms:
          - liquid_logic
          - mosaic
      - name: description
        type: VARCHAR(255)
        cms:
          - liquid_logic
          - mosaic
      - name: product_type
        type: VARCHAR(50)
        cms:
          - liquid_logic
