<la_id>:    
  la_code: <la_id>
  la_name: <la_name>

  deployment_system: # META-ELEMENT: {"type": "deployment_system"} # vals here must be type(str)
    cms: <null>
    cms_db: <null> 
    db_vers: <null> 
    db_compatibility: <null> # 60-120  
    ics_universe_vers: <null>
    data_warehouse_vers: <null>
    front_end_vers: <null>

  config_metadata: # META-ELEMENT: {"type": "config_metadata"}
    last_updated: 2024-09-25
    version: 1.0
    updated_by: rharrison
    change_description: <null>
    approved_by: <null>
    documentation_link: https://data-to-insight.github.io/ssd-data-model

  header: # META-ELEMENT: {"type": "header"}
    header_text: |
      *********************************************************************************************************
      STANDARD SAFEGUARDING DATASET EXTRACT 
      https://data-to-insight.github.io/ssd-data-model/
      We strongly recommend that initial pilot/trials of SSD scripts occur in a development|test environment.
      The SQL script is non-destructive. SSD clean-up scripts are available seperately, these are destructive.
      *********************************************************************************************************

  settings: # EXTRACT SETTINGS
    extract_parameters: # META-ELEMENT: {"type": "ssd_timeframe"}
      ssd_timeframe_years: 5
      ssd_sub1_range_years: 1
      # CaseloadLastSept30th: "2024-09-30" # currently set in sql based on currDate->prevSept30th

    persistent_ssd: # META-ELEMENT: {"type": "persistent_ssd"}
    # if temp tables set true, all FK/IDX must also be true for full removal to avoid warnings
      deploy_temp_tables: false  # true = temporary tables(must also set global_sql_tag_remove:fk|idx to true ), false = persistent tables
      temp_table_prefix: <null>


    dbschema: # META-ELEMENT: {"type": "dbschema"}  # la schema definition
      data_source_schema: HDM.Child_Social 
      deployment_database_name: HDM_Local             # i.e. default tablespace
      deployment_schema_name: <null> # If this is set to null, and deploy_temp_tables: false, SSD is installed in current default db schema

    dev_setup: # META-ELEMENT: {"type": "dev_setup"} 
      no_count_on: false # true = SET NOCOUNT ON; / false = SET NOCOUNT OFF;



# REMOVE | CLEAN UP SQL
  # remove ALL in script refs of named META-ELEMENT: block type using: true/false flags
  # overides and precedes localised settings in <named_sql_tag_remove:>
  global_sql_tag_remove:
    remove_drop_table: true                 # all blocks tagged with -- META-ELEMENT: {"type": "drop_table"}    - lossy/destructive SQL
    remove_insert_data: false               # all blocks tagged with -- META-ELEMENT: {"type": "insert_data"}   - towards creating no-data SSD structure
    remove_test: true                       # all blocks tagged with -- META-ELEMENT: {"type": "test"}          - towards silent running
    remove_console: false                   # all blocks tagged with -- META-ELEMENT: {"type": "console_output"} - towards silent running
    remove_deployment_status_note: true     # all blocks tagged with -- META-ELEMENT: {"type": "deployment_status_note"}
    remove_ssd_non_core_modifications: true # all blocks tagged with -- META-ELEMENT: {"type": "ssd_non_core_modifications"}
 
    # all the below set to true if deploy_temp_tables: true
    remove_create_pk: false                  # all blocks tagged with -- META-ELEMENT: {"type": "create_pk"}
    remove_create_fk: false                  # all blocks tagged with -- META-ELEMENT: {"type": "create_fk"}
    remove_create_idx: false                 # all blocks tagged with -- META-ELEMENT: {"type": "create_idx"}


# BESPOKE SQL | SCHEMA
  named_sql_container_remove:
  - involvements_history

  # remove named object/table level references <within> labelled parent block type
  # e.g.  [parent block] -- META-CONTAINER: {"type": "table", "name": "ssd_family"}
  #       [child type meta block]-- META-ELEMENT: {"type": "drop_table"}
  named_sql_tag_remove:
    remove_drop_table:           # {"type": "drop_table"}
    - <null> 
    remove_create_table:         # {"type": "create_table"}
    - <null> 
    remove_insert_data:          # {"type": "insert_data"}
    - ssd_ehcp_active_plans # non-core table
    - ssd_ehcp_named_plan   # non-core table
    - ssd_ehcp_assessment   # non-core table
    - ssd_ehcp_requests     # non-core table     
    - ssd_sen_need          # non-core table
    - ssd_pre_proceedings       # non-core table
    - ssd_voice_of_child    # non-core table
    - ssd_s251_finance
    remove_create_pk:           # {"type": "create_pk"}
    - <null> 
    remove_create_fk:           # {"type": "create_fk"}
     - ssd_ehcp_active_plans
     - ssd_ehcp_named_plan
     - ssd_ehcp_assessment
     - ssd_ehcp_requests
     - ssd_sen_need
     - ssd_pre_proceedings
     - ssd_voice_of_child
     - ssd_s251_finance
     - ssd_cla_reviews # data issue
     - ssd_cla_previous_permanence # data issue
     - ssd_cla_visits # data issue
     - ssd_sdq_scores # data issue
     - ssd_care_leavers # data issue
     - ssd_permanence # data issue
     - ssd_cp_visits # possible data issues
     - ssd_cp_reviews # possible data issues
     - ssd_department # possible data issues
  
    remove_create_idx:          # {"type": "create_idx"}
    - ssd_ehcp_active_plans
    - ssd_ehcp_named_plan
    - ssd_ehcp_assessment
    - ssd_ehcp_requests
    - ssd_sen_need
    - ssd_pre_proceedings
    - ssd_voice_of_child
    - ssd_s251_finance

# BESPOKE STRUCTURE CHANGES
  extract_sql_custom_la:
   customise_db_schema:
    - ssd_item_ref: <null> # compulsory: needed to identify item level edits 
      ssd_table: <null> # compulsory: to ensure correct container block to effect item level edits 
      ssd_item_field_name: <null> 
      la_field_name: <null>  # if replacing local field name in LA system
      la_table_name: <null>  # if replacing local table name in LA system
      la_datatype: <null> # undesirable to make change here, but scope for it
      la_datatype_size: <null> # la change change to enable extended local reporting from ssd

    
    # duplicate the above block to add further bespoke changes



