/* interogate Azeus DB */

-- Obtain available schemas in case tables cross schemas
SELECT DISTINCT OWNER
FROM ALL_OBJECTS
WHERE OWNER IS NOT NULL;


-- List of tables derived from the stat-returns Azeus spec supplied
DECLARE
    schema_name VARCHAR2(100) := 'YourSchema'; -- Replace 'YourSchema' with your schema name

-- List of table names
WITH TableNames AS (
SELECT 'ADOPTER_APP' AS TableName FROM DUAL
UNION ALL
SELECT 'PLCMT' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_COMM' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_DISAB' AS TableName FROM DUAL
UNION ALL
SELECT 'ADOPTER_APP_ACT' AS TableName FROM DUAL
UNION ALL
SELECT 'ADOPTER_REL' AS TableName FROM DUAL
UNION ALL
SELECT 'ASMT' AS TableName FROM DUAL
UNION ALL
SELECT 'CASE_ACT' AS TableName FROM DUAL
UNION ALL
SELECT 'CASE_RVW' AS TableName FROM DUAL
UNION ALL
SELECT 'CASE_EPISODE' AS TableName FROM DUAL
UNION ALL
SELECT 'CASEWORKER' AS TableName FROM DUAL
UNION ALL
SELECT 'CP_STATUS' AS TableName FROM DUAL
UNION ALL
SELECT 'EMP_ID' AS TableName FROM DUAL
UNION ALL
SELECT 'INIT_CONT' AS TableName FROM DUAL
UNION ALL
SELECT 'REFERRAL' AS TableName FROM DUAL
UNION ALL
SELECT 'KEYWORKER_HIST' AS TableName FROM DUAL
UNION ALL
SELECT 'MISSING_EP' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LA_STATUS' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LA_LGL_STATUS' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_PROV_ID' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_ADDR' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_PROV_ADDR' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_EDUC_NEED' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_ID' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_IMMIG_STATUS' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_IMMUNISATION_DT' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LAC_MED' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LC_ACCOMM' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LC_ACT' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LC_CAT' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_LC_CONT' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_OFFN' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_PLAN' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_REL' AS TableName FROM DUAL
UNION ALL
SELECT 'SVC_USR_SUBSTANCE_MISUSE' AS TableName FROM DUAL

)

-- retrieve column names for each table
SELECT tn.TableName, COLUMN_NAME
FROM TableNames tn
JOIN ALL_TAB_COLUMNS tc ON tn.TableName = tc.TABLE_NAME
WHERE tc.OWNER = schema_name
ORDER BY tn.TableName, COLUMN_ID;


