/* 
INSTANCE INIT INVESTIGATION 
*/

-- 
SET TIMING ON;

-- check current user
SELECT USER FROM DUAL;

-- check current schema
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL;

-- check users direct object privs
SELECT PRIVILEGE
FROM ALL_TAB_PRIVS
WHERE GRANTEE = USER
AND TABLE_NAME = 'ssd_source_table'
AND PRIVILEGE = 'SELECT';

-- check users role based privs
SELECT GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = USER
UNION
SELECT PRIVILEGE
FROM ROLE_TAB_PRIVS
WHERE ROLE IN (SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = USER)
AND TABLE_NAME = 'ssd_source_table'
AND PRIVILEGE = 'SELECT';

-- version infos for Oracle and components
SELECT BANNER 
FROM V$VERSION 
WHERE BANNER LIKE 'Oracle%';


-- Search for relevant field/table(s)
SELECT TABLE_NAME, COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE UPPER(COLUMN_NAME) = UPPER('Legal_Status')
-- WHERE UPPER(COLUMN_NAME) LIKE UPPER('%Legal_Status%')
AND UPPER(TABLE_NAME) IN (UPPER('Person_Legal_Statuses'), UPPER('Children_In_Care'));

/* 
END INSTANCE INIT INVESTIGATION 
*/


