USE PLACEHOLDER_DB_NAME;
SELECT EH_Episode_ID, Child_Unique_ID, EH_Episode_Start_Date, EH_Episode_End_Date, EH_Episode_Reason_for_Involvement, EH_Episode_End_Reason, EH_Episode_Allocated_Organisation, EH_Episode_Allocated_Worker FROM early_help_episodes;
SELECT Named_Plan_ID, Assessment_ID, Start_Date, Cease_Date, Cease_Reason FROM named_plan;
SELECT Assessment_ID, Child_Unique_ID, Assessment_Start_Date, Child_Seen_During_Assessment, Assessment_Authorised_Date, Assessment_Outcome, Assessment_Completed_by_Team, Assessment_Completed_by_Worker FROM assessments;
SELECT Contact_ID, Child_Unique_ID, Date_of_Contact, Contact_Source, Contact_Outcome_ FROM contacts;
SELECT CIN_Plan_ID, Child_Unique_ID, CINPlanStartDate, CIN_Plan_End_Date, CIN_Allocated_Team, CIN_Allocated_Worker FROM cin_plans;
SELECT Missing_Episode_ID, Episode_ID, Missing_Episode_Start, Episode_Type_(Missing/_Absent), Missing_Episode_End, RHI_Offered, RHI_Accepted FROM missing;
SELECT CIN_Referral_ID, Child_Unique_ID, CIN_Referral_Date, CIN_Referral_Source, CIN_Referral_Outcome, CIN_Closure_Reason, CIN_Closure_Date, CIN_Referral_Completed_by_Team, CIN_Referral_Completed_by_Worker FROM cin_episodes;
SELECT Review_ID, Risks_to_child_at_this_conference FROM risks_to_child_at_this_conference;
SELECT Child_Unique_ID, Immigration_Status, Immigration_Status_Start, Immigration_Status_End FROM immigration_status;
SELECT Review_ID, CP_Plan_ID, Review_Due_Date, Date_of_Review, cp_plan_continues, quorate, Child's_Participation, quality_of_representation, cp_progress_made FROM cp_reviews;
SELECT SEN_Need_ID, Plan_ID, SEN_Type, SEN_Type_Rank FROM sen_need;
SELECT Review_ID, What_is_the_chosen_plan_for_this_child/young_person? FROM care_plan;
SELECT LAchildID, Sex, Gender, Ethnicity, PersonBirthDate, UPN, UPNunknown, SENDFlag FROM child;
SELECT UPN, Child_Unique_ID FROM send;
SELECT CP_Plan_ID, CP_Visit_ID, Date_of_Visit, Child_Seen, Child_Seen_Alone, Child_Bedroon_Seen FROM cp_visits;
SELECT Care_Leaver_Table_ID, Child_Unique_ID, Eligibility_Status/_Category, In_Touch_Category, Latest_Date_of_Contact, Accommodation, Suitability_of_Accommodation, Activity_Status, Latest_Pathway_Plan_Review_Date, Allocated_Personal_Advisor, Allocated_Team, Allocated_Worker FROM care_leavers;
SELECT CIN_Visit_ID, CIN_Plan_ID, CIN_Visit_Date, Child_Seen, Child_Seen_Alone, Child_Bedroom_Seen FROM cin_visits;
SELECT S47_Enquiry_ID, Child_Unique_ID, s47_equiry_start, S47_Start_Date, S47_Completed_Date, S47_Outcome, cp_conf_date, cp_conf_outcome, s47_allocated_team, s47_allocated_worker FROM s47_enquiry;
SELECT Plan_ID, Request_ID, Last_Review FROM active_plans;
SELECT sw_reg_number, Agency_worker, Role_within_the_organisation, num_cases, Qualification_level FROM worker;
SELECT Child_Unique_ID, Disability_Code FROM disability;
SELECT Assessment_ID, Assessment_Factors FROM assessment_factors;
SELECT Mother's_Child_Unique_ID, Child_Unique_ID_(Mother), MC_DOB FROM mother;
SELECT CP_Plan_ID, Child_Unique_ID, CP_Plan_Start_Date, CP_Plan_End_Date, CP_Plan_Allocated_Team, CP_Plan_Allocated_Worker FROM cp_plans;
SELECT CP_Plan_ID, Category_of_Abuse, Category_of_Abuse_Start_Date FROM category_of_abuse;
SELECT SDQ_ID, Child_Unique_ID, SDQ_Completed_Date, SDQ_Score FROM sdq_scores;
SELECT Assessment_ID, Request_ID, Assessment_Outcome_Date, Assessment_Outcome FROM assessment;
SELECT Placement_ID, Episode_ID, Placement_Start_Date, Placement_Type, URN_of_Placement, LA_of_Placement, Placement_Provider, Placement_Postcode, Placement_End_Date, Reason_for_Placement_Change FROM placement;
SELECT Review_ID, Episode_ID, CLA_Review_Due_Date, CLA_Review_Date, child_involved, sw_met_child, Participation_code, CP_meets_childs_need, permanence_plan_in_place, last_iro, previously_Adopted, Date_of_Previous_Permanence_Order, Previous_Permanence_Option, Previous_Permanence_Arranged_LA, Child_convicted_during_the_year, Health_surveillance_checks_up_to_date, Date_of_Last_Health_Assessment, Date_of_Last_Dental_Check, Immunisations_up_to_Date, substance_misuse, substance_invevention FROM cla_reviews;
SELECT Request_ID, UPN, Received_Date, Request_Outcome_Date, Request_Outcome FROM requests;
SELECT Legal_Status_ID, Child_Unique_ID, Legal_Status, Legal_Status_Start_Date, Legal_Status_End_Date FROM legal_status;
SELECT Family_identifier, Child_Unique_ID FROM family;
SELECT Child_Unique_ID, Date_of_ADM_Decision_, Date_of_FFA/_CP_Decision, Date_the_entered_Care, Date_of_Placement/_Freeing_Order, Date_Placed_for_Adoption, Date_matched, Date_placed, Decision_date, foster_date, sibling_group, number_siblings_placed_together, number_siblings_placed_seperate, URN_of_Placement, Not_placed_reason, Date_of_Order , Type_of_Order, Status_of_Special_Guardian, Age_of_Special_Guardian FROM permanence;
SELECT _Visit_ID, Episode_ID, Date_of_Visit, Child_Seen, Child_Seen_Alone FROM cla_visits;
SELECT Episode_ID, Child_Unique_ID, Date_Episode_Commenced, Reason_for_New_CLA_Episode, DEC, REC, Allocated_Team, Allocated_Worker FROM cla_episodes;
SELECT Address, Child_Unique_ID, Address_Start_Date/_From, Address_End_Date/_To FROM address;
